Repository owncloud/announcementcenter, pull requests merged in 2018-12, with the labels that each got.

#112 Standardize CI and move unit tests to Unit folder
  .drone.yml
  .gitignore
  .phan/config.php
  Makefile
  lib/BackgroundJob.php
  lib/Controller/PageController.php
  phpstan.neon
  phpunit.xml
  tests/Unit/Activity/ExtensionTest.php
  tests/Unit/AppInfo/AppTest.php
  tests/Unit/AppInfo/ApplicationTest.php
  tests/Unit/AppInfo/RoutesTest.php
  tests/Unit/BackgroundJobTest.php
  tests/Unit/Controller/PageControllerTest.php
  tests/Unit/ManagerTest.php
  tests/Unit/Notification/NotifierTest.php
  tests/Unit/TestCase.php
  tests/bootstrap.php
  vendor-bin/owncloud-codestyle/composer.json
  vendor-bin/phan/composer.json
  vendor-bin/phpstan/composer.json
Labels: 3 - To Review, Drone, QA-team

#110 Release 1.2.1
  CHANGELOG.md
  Makefile
  appinfo/info.xml
Labels: 3 - To Review

#114 Adjust build status for drone
  README.md
Labels: 4 - To Release, QA-team
