Repository owncloud/announcementcenter, pull requests merged in 2020-04, with the labels that each got.

#145 [Tests-Only] Update phpstan to latest version
  Makefile
  lib/Activity/Extension.php
  lib/Notification/Notifier.php
  phpstan.neon
  vendor-bin/phpstan/composer.json
Labels: 4 - To Release, QA-team

#146 [Tests-Only] Run phpstan in CI
  .drone.star
Labels: QA-team

#147 [Tests-Only] Bump phan 2.7
  .drone.star
  vendor-bin/phan/composer.json
Labels: 4 - To Release, QA-team

#148 Drop PHP 7.1
  .drone.star
  composer.json
  composer.lock
Labels: 3 - To Review, QA-team

#149 Adjust drone pipelines for PHP 7.4
  .drone.star
  .gitignore
Labels: 3 - To Review, QA-team
